const cityLabels = 
[
  { label: 'Bắc Giang', value: 'bacgiang' },
  { label: 'Bắc Kạn', value: 'backan' },
  { label: 'Cao Bằng', value: 'caobang' },
  { label: 'Hà Giang', value: 'hagiang' },
  { label: 'Lạng Sơn', value: 'langson' },
  { label: 'Phú Thọ', value: 'phutho' },
  { label: 'Quảng Ninh', value: 'quangninh' },
  { label: 'Thái Nguyên', value: 'thainguyen' },
  { label: 'Tuyên Quang', value: 'tuyenquang' },
  { label: 'Yên Bái', value: 'yenbai' },
  { label: 'Điện Biên', value: 'dienbien' },
  { label: 'Hòa Bình', value: 'hoabinh' },
  { label: 'Lai Châu', value: 'laichau' },
  { label: 'Sơn La', value: 'sonla' },
  { label: 'Bắc Ninh', value: 'bacninh' },
  { label: 'Hà Nam', value: 'hanam' },
  { label: 'Hải Dương', value: 'haiduong' },
  { label: 'Hưng Yên', value: 'hungyen' },
  { label: 'Nam Định', value: 'namdinh' },
  { label: 'Ninh Bình', value: 'ninhbinh' },
  { label: 'Thái Bình', value: 'thaibinh' },
  { label: 'Vĩnh Phúc', value: 'vinhphuc' },
  { label: 'Hà Nội', value: 'hanoi' },
  { label: 'Hải Phòng', value: 'haiphong' },
  { label: 'Hà Tĩnh', value: 'hatinh' },
  { label: 'Nghệ An', value: 'nghean' },
  { label: 'Quảng Bình', value: 'quangbinh' },
  { label: 'Quảng Trị', value: 'quangtri' },
  { label: 'Thanh Hóa', value: 'thanhhoa' },
  { label: 'Thừa Thiên-Huế', value: 'thuathienhue' },
  { label: 'Đắk Lắk', value: 'daklak' },
  { label: 'Đắk Nông', value: 'daknong' },
  { label: 'Gia Lai', value: 'gialai' },
  { label: 'Kon Tum', value: 'kontum' },
  { label: 'Lâm Đồng', value: 'lamdong' },
  { label: 'Bình Định', value: 'binhdinh' },
  { label: 'Bình Thuận', value: 'binhthuan' },
  { label: 'Khánh Hòa', value: 'khanhhoa' },
  { label: 'Ninh Thuận', value: 'ninhthuan' },
  { label: 'Phú Yên', value: 'phuyen' },
  { label: 'Quảng Nam', value: 'quangnam' },
  { label: 'Quảng Ngãi', value: 'quangngai' },
  { label: 'Đà Nẵng', value: 'danang' },
  { label: 'Bà Rịa-Vũng Tàu', value: 'bariavungtau' },
  { label: 'Bình Dương', value: 'binhduong' },
  { label: 'Bình Phước', value: 'binhphuoc' },
  { label: 'Đồng Nai', value: 'dongnai' },
  { label: 'Tây Ninh', value: 'tayninh' },
  { label: 'Hồ Chí Minh', value: 'hochiminh' },
  { label: 'An Giang', value: 'angiang' },
  { label: 'Bạc Liêu', value: 'baclieu' },
  { label: 'Bến Tre', value: 'bentre' },
  { label: 'Cà Mau', value: 'camau' },
  { label: 'Đồng Tháp', value: 'dongthap' },
  { label: 'Hậu Giang', value: 'haugiang' },
  { label: 'Kiên Giang', value: 'kiengiang' },
  { label: 'Long An', value: 'longan' },
  { label: 'Sóc Trăng', value: 'soctrang' },
  { label: 'Tiền Giang', value: 'tiengiang' },
  { label: 'Trà Vinh', value: 'travinh' },
  { label: 'Vĩnh Long', value: 'vinhlong' },
  { label: 'Cần Thơ', value: 'cantho' }
]

export function selectNameCity(value) {
  const city = cityLabels.find((item) => item.value === value);
  return city.label;
};

export default cityLabels;
